# server port
server.port=8080

##database setting
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=kh11
spring.datasource.password=kh11

##spring actuator setting 
management.endpoints.web.exposure.include=mappings,beans,env

#DBCP(DataBase Connection Pool) : 데이터베이스 최적화에 사용되는 것 
#max-total 총 개수
#max-idle 최대 유휴 개수 총 개수의 50%를 넘으면 안된다. 
#min-idle 최소 유휴 개수 0개 이게 1이상이면 자원을 많이 잡아먹는다. 
#max-wait-millis 최대 대기시간 단위시간 (ms)밀리세크 
spring.datasource.dbcp2.max-total=20
spring.datasource.dbcp2.min-idle=0
spring.datasource.dbcp2.max-idle=10
spring.datasource.dbcp2.max-wait-millis=3000 

# file upload setting (multipart resolver)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=10MB

# 404 error 설정(404 error : 컨트롤러가 없을 때 발생하는 에러)
spring.mvc.throw-exception-if-no-handler-found=true

# 정적 자원에 대한 처리를 진행하겠다. false면 정적자원 사용불가. 
#spring.web.resources.add-mappings=true 

# static resource path setting (만약에 주소 /static으로 시작하면 exception을 발생시키지 않도록 제어) 
spring.mvc.static-path-pattern=/static/**
spring.web.resources.static-locations=classpath:/static/


# 파일 업로드 경로 커스텀 설정
custom.fileupload.path=D:/upload

